changelog:
  categories:
  - title: Breaking Changes
    labels:
    - breaking-change
  - title: main 
    labels:
    - feature
  - title: Bug fixes 
    labels:
    - bug
  - title: Other Changes
    labels:
       - "*"
